version: '3.8'
    
services:
  app:
    image: laravel/app:1.0
    build: ./app
    container_name: 'laravel_app'
    ports:
      - '8000:8000'
    stdin_open: true
    tty: true
    working_dir: '/var/www/html'
    volumes:
      - ./app/php.ini:/usr/local/etc/php/php.ini
      - ../app:/var/www/html
    depends_on:
      - db

  db:
    image: laravel/mysql:1.0
    build: ./db
    container_name: 'laravel_db'
    expose: 
      - "3306"
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my
      - MYSQL_USER=my
      - MYSQL_PASSWORD=my
    volumes:
      - ../db/database:/var/lib/mysql
      - ../db/init:/docker-entrypoint-initdb.d
